version: "3.8"
services:
  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    restart: always
    volumes:
      - ./data:/data
    ports:
      - 9000:9000
      - 9001:9001
  objx:
    image: ghcr.io/picosh/objx/objx
    env_file:
      - .env
    volumes:
      - ./ssh_data:/ssh_data
    restart: always
    ports:
      - 2222:2222
